In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

data = {
    'Weather': ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'],
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)

df['Weather'] = df['Weather'].map({'Sunny': 0, 'Overcast': 1, 'Rainy': 2})
df['Temperature'] = df['Temperature'].map({'Hot': 0, 'Mild': 1, 'Cool': 2})
df['Play'] = df['Play'].map({'No': 0, 'Yes': 1})

X = df[['Weather', 'Temperature']]
y = df['Play']

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

new_data = [[1, 1]]  # Overcast (1), Mild (1)
prediction = knn.predict(new_data)

play_result = "Yes" if prediction[0] == 1 else "No"
print(f"Prediction for Overcast and Mild: {play_result}")

y_pred = knn.predict(X)
conf_matrix = confusion_matrix(y, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_report(y, y_pred))


Prediction for Overcast and Mild: Yes

Confusion Matrix:
[[3 2]
 [1 8]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.80      0.89      0.84         9

    accuracy                           0.79        14
   macro avg       0.78      0.74      0.75        14
weighted avg       0.78      0.79      0.78        14



C:\Users\LAPTOP WORLD\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [1]:
import numpy as np
from collections import Counter

training_data = [
    {'features': (7, 7), 'class': 'Bad'},
    {'features': (7, 4), 'class': 'Bad'},
    {'features': (3, 4), 'class': 'Good'},
    {'features': (1, 4), 'class': 'Good'}
]

query_instance = (3, 7)

def euclidean_distance(point1, point2):
    return np.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)

distances = []
for sample in training_data:
    distance = euclidean_distance(query_instance, sample['features'])
    distances.append((distance, sample['class']))

distances.sort(key=lambda x: x[0])

k = 3
nearest_neighbors = [dist[1] for dist in distances[:k]]

prediction = Counter(nearest_neighbors).most_common(1)[0][0]

print(f"Prediction for the query instance {query_instance}: {prediction}")
print("Distances to each training sample:", distances)


Prediction for the query instance (3, 7): Good
Distances to each training sample: [(np.float64(3.0), 'Good'), (np.float64(3.605551275463989), 'Good'), (np.float64(4.0), 'Bad'), (np.float64(5.0), 'Bad')]


In [2]:
import numpy as np
from collections import Counter

training_data = [
    {'features': (7, 7), 'class': 'Bad'},
    {'features': (7, 4), 'class': 'Bad'},
    {'features': (3, 4), 'class': 'Good'},
    {'features': (1, 4), 'class': 'Good'}
]

query_instance = (3, 7)

def euclidean_distance(point1, point2):
    return float(np.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2))

distances = []
for sample in training_data:
    distance = euclidean_distance(query_instance, sample['features'])
    distances.append((distance, sample['class']))

distances.sort(key=lambda x: x[0])

k = 3
nearest_neighbors = [dist[1] for dist in distances[:k]]

prediction = Counter(nearest_neighbors).most_common(1)[0][0]

print(f"Prediction for the query instance {query_instance}: {prediction}")
print("Distances to each training sample:", distances)


Prediction for the query instance (3, 7): Good
Distances to each training sample: [(3.0, 'Good'), (3.605551275463989, 'Good'), (4.0, 'Bad'), (5.0, 'Bad')]


In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
# New dataset
data = [
    {'Age': 24, 'Salary': 50, 'Experience': 1, 'Loan Approval': 'No'},
    {'Age': 28, 'Salary': 60, 'Experience': 3, 'Loan Approval': 'No'},
    {'Age': 35, 'Salary': 80, 'Experience': 7, 'Loan Approval': 'Yes'},
    {'Age': 40, 'Salary': 100, 'Experience': 10, 'Loan Approval': 'Yes'},
    {'Age': 45, 'Salary': 120, 'Experience': 15, 'Loan Approval': 'Yes'},
    {'Age': 23, 'Salary': 45, 'Experience': 0, 'Loan Approval': 'No'},
    {'Age': 30, 'Salary': 70, 'Experience': 4, 'Loan Approval': 'No'},
    {'Age': 33, 'Salary': 85, 'Experience': 8, 'Loan Approval': 'Yes'},
    {'Age': 38, 'Salary': 90, 'Experience': 12, 'Loan Approval': 'Yes'},
    {'Age': 42, 'Salary': 110, 'Experience': 14, 'Loan Approval': 'Yes'},
    {'Age': 48, 'Salary': 130, 'Experience': 18, 'Loan Approval': 'Yes'},
    {'Age': 27, 'Salary': 65, 'Experience': 2, 'Loan Approval': 'No'},
    {'Age': 31, 'Salary': 75, 'Experience': 5, 'Loan Approval': 'No'},
    {'Age': 29, 'Salary': 55, 'Experience': 3, 'Loan Approval': 'No'}
]
df = pd.DataFrame(data)
X = df[['Age', 'Salary', 'Experience']]  
y = df['Loan Approval']  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)  
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
query = [[32, 85, 6]] 
prediction = knn.predict(query)
print(f"Prediction for the new instance (Age=32, Salary=85K, Experience=6): {prediction[0]}")
cm = confusion_matrix(y_test, y_pred, labels=['Yes', 'No'])
print("Confusion Matrix:")
print(cm)


Prediction for the new instance (Age=32, Salary=85K, Experience=6): Yes
Confusion Matrix:
[[1 0]
 [1 3]]


C:\Users\LAPTOP WORLD\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [2]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
# New dataset
data = [
    {'Age': 24, 'Salary': 50, 'Experience': 1, 'Loan Approval': 'No'},
    {'Age': 28, 'Salary': 60, 'Experience': 3, 'Loan Approval': 'No'},
    {'Age': 35, 'Salary': 80, 'Experience': 7, 'Loan Approval': 'Yes'},
    {'Age': 40, 'Salary': 100, 'Experience': 10, 'Loan Approval': 'Yes'},
    {'Age': 45, 'Salary': 120, 'Experience': 15, 'Loan Approval': 'Yes'},
    {'Age': 23, 'Salary': 45, 'Experience': 0, 'Loan Approval': 'No'},
    {'Age': 30, 'Salary': 70, 'Experience': 4, 'Loan Approval': 'No'},
    {'Age': 33, 'Salary': 85, 'Experience': 8, 'Loan Approval': 'Yes'},
    {'Age': 38, 'Salary': 90, 'Experience': 12, 'Loan Approval': 'Yes'},
    {'Age': 42, 'Salary': 110, 'Experience': 14, 'Loan Approval': 'Yes'},
    {'Age': 48, 'Salary': 130, 'Experience': 18, 'Loan Approval': 'Yes'},
    {'Age': 27, 'Salary': 65, 'Experience': 2, 'Loan Approval': 'No'},
    {'Age': 31, 'Salary': 75, 'Experience': 5, 'Loan Approval': 'No'},
    {'Age': 29, 'Salary': 55, 'Experience': 3, 'Loan Approval': 'No'}
]
df = pd.DataFrame(data)
X = df[['Age', 'Salary', 'Experience']]  
y = df['Loan Approval']  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
query = [[32, 85, 6]]  
prediction = knn.predict(query)
print(f"Prediction for the new instance (Age=32, Salary=85K, Experience=6): {prediction[0]}")
cm = confusion_matrix(y_test, y_pred, labels=['Yes', 'No'])
print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, labels=['Yes', 'No']))


Prediction for the new instance (Age=32, Salary=85K, Experience=6): Yes
Confusion Matrix:
[[1 0]
 [1 3]]

Classification Report:
              precision    recall  f1-score   support

         Yes       0.50      1.00      0.67         1
          No       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5



C:\Users\LAPTOP WORLD\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [3]:
import numpy as np
from collections import Counter
X_train = np.array([[7, 7], [7, 4], [3, 4], [1, 4]])
y_train = np.array(['Bad', 'Bad', 'Good', 'Good'])
query_instance = np.array([3, 7])
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))
    
distances = []
for i in range(len(X_train)):
    dist = euclidean_distance(query_instance, X_train[i])
    distances.append((dist, y_train[i]))
    
distances.sort(key=lambda x: x[0])
neighbors = distances[:3]
prediction = Counter([neighbor[1] for neighbor in neighbors]).most_common(1)[0][0]
print(f"Prediction: {prediction}")
print("\nDistances to each training sample:")
for dist, label in distances:
    print(f"Distance: {dist}, Label: {label}")


Prediction: Good

Distances to each training sample:
Distance: 3.0, Label: Good
Distance: 3.605551275463989, Label: Good
Distance: 4.0, Label: Bad
Distance: 5.0, Label: Bad
