In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

data = {
    'Gender': ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female'],
    'Height': [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    'Weight': [180, 190, 170, 165, 100, 150, 130, 150],
    'Foot_Size': [12, 11, 12, 10, 6, 8, 7, 9]
}

df = pd.DataFrame(data)
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])

X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']

model = DecisionTreeClassifier()
model.fit(X, y)

new_entry = [[5.85, 160, 10]]
predicted_gender = model.predict(new_entry)
gender_label = encoder.inverse_transform(predicted_gender)
print(f"The predicted gender is: {gender_label[0]}")


The predicted gender is: male


C:\Users\LAPTOP WORLD\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

data = {
    'Gender': ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female'],
    'Height': [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    'Weight': [180, 190, 170, 165, 100, 150, 130, 150],
    'Foot_Size': [12, 11, 12, 10, 6, 8, 7, 9]
}

df = pd.DataFrame(data)
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])

X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']

model = DecisionTreeClassifier()
model.fit(X, y)

new_entry = [[5.85, 160, 10]]
predicted_gender = model.predict(new_entry)
gender_label = encoder.inverse_transform(predicted_gender)
print(f"The predicted gender is: {gender_label[0]}")

new_data = {
    'Gender': encoder.transform([gender_label[0]])[0],
    'Height': new_entry[0][0],
    'Weight': new_entry[0][1],
    'Foot_Size': new_entry[0][2]
}

df = pd.concat([df, pd.DataFrame([new_data])], ignore_index=True)
print("\nUpdated Dataset:")
print(df)


The predicted gender is: male

Updated Dataset:
   Gender  Height  Weight  Foot_Size
0       1    6.00     180         12
1       1    5.92     190         11
2       1    5.58     170         12
3       1    5.92     165         10
4       0    5.00     100          6
5       0    5.50     150          8
6       0    5.42     130          7
7       0    5.75     150          9
8       1    5.85     160         10


C:\Users\LAPTOP WORLD\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [4]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

data = [
    ['male', 6.00, 180, 12],
    ['male', 5.92, 190, 11],
    ['male', 5.58, 170, 12],
    ['male', 5.92, 165, 10],
    ['female', 5.00, 100, 6],
    ['female', 5.50, 150, 8],
    ['female', 5.42, 130, 7],
    ['female', 5.75, 150, 9]
]

data = np.array(data, dtype=object)
encoder = LabelEncoder()
data[:, 0] = encoder.fit_transform(data[:, 0])

X = data[:, 1:].astype(float)
y = data[:, 0].astype(int)

model = DecisionTreeClassifier()
model.fit(X, y)

new_entry = np.array([[5.85, 160, 10]])
predicted_gender = model.predict(new_entry)
gender_label = encoder.inverse_transform(predicted_gender)
print(f"The predicted gender is: {gender_label[0]}")

new_row = np.array([[predicted_gender[0], new_entry[0][0], new_entry[0][1], new_entry[0][2]]])
data = np.vstack((data, new_row))

print("\nUpdated Dataset:")
for row in data:
    print(row)


The predicted gender is: male

Updated Dataset:
[1 6.0 180 12]
[1 5.92 190 11]
[1 5.58 170 12]
[1 5.92 165 10]
[0 5.0 100 6]
[0 5.5 150 8]
[0 5.42 130 7]
[0 5.75 150 9]
[1.0 5.85 160.0 10.0]


In [5]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

data = [
    ['male', 6.00, 180, 12],
    ['male', 5.92, 190, 11],
    ['male', 5.58, 170, 12],
    ['male', 5.92, 165, 10],
    ['female', 5.00, 100, 6],
    ['female', 5.50, 150, 8],
    ['female', 5.42, 130, 7],
    ['female', 5.75, 150, 9]
]

data = np.array(data, dtype=object)
encoder = LabelEncoder()
data[:, 0] = encoder.fit_transform(data[:, 0])

X = data[:, 1:].astype(float)
y = data[:, 0].astype(int)

model = DecisionTreeClassifier()
model.fit(X, y)

new_entry = np.array([[5.85, 160, 10]])
predicted_gender = model.predict(new_entry)
gender_label = encoder.inverse_transform(predicted_gender)
print(f"The predicted gender is: {gender_label[0]}")

new_row = np.array([[predicted_gender[0], new_entry[0][0], new_entry[0][1], new_entry[0][2]]])
data = np.vstack((data, new_row))

print("\nUpdated Dataset:")
for row in data:
    print(row)


The predicted gender is: male

Updated Dataset:
[1 6.0 180 12]
[1 5.92 190 11]
[1 5.58 170 12]
[1 5.92 165 10]
[0 5.0 100 6]
[0 5.5 150 8]
[0 5.42 130 7]
[0 5.75 150 9]
[1.0 5.85 160.0 10.0]


In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

data = [
    [24, 50, 1, 'No'],
    [28, 60, 3, 'No'],
    [35, 80, 7, 'Yes'],
    [40, 100, 10, 'Yes'],
    [45, 120, 15, 'Yes'],
    [23, 45, 0, 'No'],
    [30, 70, 4, 'No'],
    [33, 85, 8, 'Yes'],
    [38, 90, 12, 'Yes'],
    [42, 110, 14, 'Yes'],
    [48, 130, 18, 'Yes'],
    [27, 65, 2, 'No'],
    [31, 75, 5, 'No'],
    [29, 55, 3, 'No']
]

data = np.array(data)
X = data[:, :-1].astype(float)
y = data[:, -1]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
model = DecisionTreeClassifier()
model.fit(X, y_encoded)

print("Enter new entry details:")
age = float(input("Age: "))
salary = float(input("Salary (in $K): "))
experience = float(input("Experience (Years): "))

new_entry = np.array([[age, salary, experience]])
prediction = model.predict(new_entry)
predicted_label = label_encoder.inverse_transform(prediction)

print(f"The predicted Loan Approval is: {predicted_label[0]}")


Enter new entry details:


Age:  23
Salary (in $K):  50000
Experience (Years):  4


The predicted Loan Approval is: No


In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

data = [
    [24, 50, 1, 'No'],
    [28, 60, 3, 'No'],
    [35, 80, 7, 'Yes'],
    [40, 100, 10, 'Yes'],
    [45, 120, 15, 'Yes'],
    [23, 45, 0, 'No'],
    [30, 70, 4, 'No'],
    [33, 85, 8, 'Yes'],
    [38, 90, 12, 'Yes'],
    [42, 110, 14, 'Yes'],
    [48, 130, 18, 'Yes'],
    [27, 65, 2, 'No'],
    [31, 75, 5, 'No'],
    [29, 55, 3, 'No']
]

data = np.array(data)
X = data[:, :-1].astype(float)
y = data[:, -1]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

model = DecisionTreeClassifier()
model.fit(X, y_encoded)

print("Enter new entry details:")
age = float(input("Age: "))
salary = float(input("Salary (in $K): "))
experience = float(input("Experience (Years): "))

new_entry = np.array([[age, salary, experience]])
prediction = model.predict(new_entry)
predicted_label = label_encoder.inverse_transform(prediction)

print(f"The predicted Loan Approval is: {predicted_label[0]}")

new_entry_with_label = np.append(new_entry, predicted_label[0])

data = np.append(data, [new_entry_with_label], axis=0)

print("\nUpdated Dataset:")
print(data)


Enter new entry details:


Age:  23
Salary (in $K):  50000
Experience (Years):  4


The predicted Loan Approval is: Yes

Updated Dataset:
[['24' '50' '1' 'No']
 ['28' '60' '3' 'No']
 ['35' '80' '7' 'Yes']
 ['40' '100' '10' 'Yes']
 ['45' '120' '15' 'Yes']
 ['23' '45' '0' 'No']
 ['30' '70' '4' 'No']
 ['33' '85' '8' 'Yes']
 ['38' '90' '12' 'Yes']
 ['42' '110' '14' 'Yes']
 ['48' '130' '18' 'Yes']
 ['27' '65' '2' 'No']
 ['31' '75' '5' 'No']
 ['29' '55' '3' 'No']
 ['23.0' '50000.0' '4.0' 'Yes']]


In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

data = [
    [24, 50, 1, 'No'],
    [28, 60, 3, 'No'],
    [35, 80, 7, 'Yes'],
    [40, 100, 10, 'Yes'],
    [45, 120, 15, 'Yes'],
    [23, 45, 0, 'No'],
    [30, 70, 4, 'No'],
    [33, 85, 8, 'Yes'],
    [38, 90, 12, 'Yes'],
    [42, 110, 14, 'Yes'],
    [48, 130, 18, 'Yes'],
    [27, 65, 2, 'No'],
    [31, 75, 5, 'No'],
    [29, 55, 3, 'No']
]

data = np.array(data)
X = data[:, :-1].astype(float)
y = data[:, -1]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

model = DecisionTreeClassifier()
model.fit(X, y_encoded)

print("Enter new entry details:")
age = float(input("Age: "))
salary = float(input("Salary (in $K): "))
experience = float(input("Experience (Years): "))

new_entry = np.array([[age, salary, experience]])
prediction = model.predict(new_entry)
predicted_label = label_encoder.inverse_transform(prediction)

print(f"The predicted Loan Approval is: {predicted_label[0]}")


Enter new entry details:


Age:  23
Salary (in $K):  50000
Experience (Years):  4


The predicted Loan Approval is: Yes
